"""new fields in user model

Revision ID: 177e68f67049
Revises: 1f6e022eba96
Create Date: 2018-09-25 20:47:13.561652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '177e68f67049'
down_revision = '1f6e022eba96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
